package dukes.greeting;

import jakarta.persistence.*;

import java.util.UUID;

// Make Greeting a Jakarta Persistence Entity that is not Cacheable
@Entity

@Cacheable(false)

public class Greeting {






    /**
     * Helpful documentation:
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/entity
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/cacheable
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/id
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/generatedvalue
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/generationtype
     */

    // Add a field called id as primary key. Use autogenerated UUIDs for the primary key
    // Add a field called message. Use String as type for the field

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    public UUID getId() { return id; }
    private UUID id;
    private String message;

    public Greeting(UUID id, String message) {
        this.id = id;
        this.message = message;
    }
    public Greeting()
    {
    }
 // getters and setters

    public String getMessage() {
        return message;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
